### ISSUE TITLE
Conflict with 5Dims storage

### ISSUE THREAD

**Issue by Muaddib-1** [snouz/Flow-Control#10]
got this trying to load Flow Control and 5Dims storage. not sure which end it's on or if they are just incompatible

Failed to load mods: Error while running setup for entity prototype "pipe-elbow" (storage-tank): next_upgrade target (5d-storage-tank-02) must have the same fast_replaceable_group (storage-tank != pipe).

**Comment by heinwessels** [comment]
Thanks for the report! This should be fixed in the latest release
