### ISSUE TITLE
Alt-mode Icon

### ISSUE THREAD

**Issue by Muaddib-1** [snouz/Flow-Control#11]
Maybe more a request than an issue.  The "alt-mode" icons on the pipes are huge, the size of a fluid tanks, completely obstructing the pipes and a good portion of the tile north of the pipe. 
Is that something that can be changed or is it the games doing because it's treating the pipes as tanks?

**Comment by heinwessels** [comment]
Ah, I wanted to fix that. I'll fix it for the next release, thanks!
